#!/bin/bash

pull_metrics() {
	if [ $# -ne 1 ] ; then
		echo "ERROR: pull_metrics used improperly used and not provided a filepath" ; exit
	fi
	local pathname=$1
	if [ $target != "All" ] ; then
		awk -v animal="$target" '$1 == animal {print $1, $2}' $pathname
	fi
	return
}

search_dir() {
	if [ $# -ne 1 ] ; then
		echo "ERROR: search_dir used improperly and not povided a directory" ; exit
	fi
	local current_dir=$1
	for item in $(ls -1A $current_dir) ; do
		local new_dir="$current_dir/$item"
		if [ -d "$new_dir" ] ; then
			if [ "$(ls -A "$new_dir")" ] ; then
				search_dir "$new_dir" 
			fi
		fi
		if [ "$item" = "$metric_name" ] ; then
			((found_metrics+=1))
			echo found metric file: "$new_dir"
			pull_metrics "$new_dir"
		fi
		item=''
	done
}

metric_name=".KS_Dir"
bear=0
dromedary=0
aardvark=0
genet=0
lemur=0
target="All"

found_metrics=0

if [ $# -eq 1 ] ; then
	target=$1
fi
echo $target
search_dir "."


if (( $found_metrics == 0 )) ; then
	echo "ERROR: No metrics files found with name $metric_name" ; exit
else
	echo "Found $found_metrics metrics files with name $metric_name"
	if [ "$target" != "All" ] ; then
		echo Total $target
	fi
fi

