#!/bin/bash

# Check if sign.c exists and is readable
[[ ! -r "sign.c" ]] && { echo "ERROR: cannot read sign.c file" ; exit ; }

# Check if squash.awk exists and is readable
[[ ! -r "squash.awk" ]] && { echo "ERROR: cannot read squash.awk file" ; exit ; }

# Compile sign.c
gcc -o sign sign.c
# Make validate that gcc command exited properly
[[ $? -ne 0 ]] && { echo "ERROR: gcc failed to compile sign.c" ; exit ; }
# Add executable persmissions if not present
[[ ! -x "sign" ]] && chmod +x sign

# Check if word list exists and is readable
[[ ! -r "/usr/share/dict/words" ]] && { echo "ERROR: cannot read '/usr/share/dict/words' word list" ; exit ; }

# Sign words > sort signed rep > squash words > count anagrams > sort by number of anagrams > output top 8
./sign < /usr/share/dict/words | sort | awk -f squash.awk | awk '{ print NF " " $0 }' | sort -nr | head -n 8
