#!/bin/bash

# Check for sign.c
[[ ! -f "sign.c" ]] && { echo "ERROR: sign.c file not found" ; exit ; }
# Check if sign.c is readable
[[ ! -r "sign.c" ]] && { echo "ERROR: sign.c file not readable" ; exit ; }

# Check for squash.awk
[[ ! -f "squash.awk" ]] && { echo "ERROR: squash.awk file not found" ; exit ; }
# Check if squash.awk is readable
[[ ! -r "squash.awk" ]] && { echo "ERROR: squash.awk file not readable" ; exit ; }

# Compile sign.c
gcc -o sign sign.c
# Make validate that gcc command exited properly
[[ $? -ne 0 ]] && { echo "ERROR: gcc failed to compile sign.c" ; exit ; }
# Validate that sign executable is a valid file
[[ ! -f "sign" ]] && { echo "ERROR: cannot find compiled sign.c executable" ; exit ; }
# Add executable persmissions if not present
[[ ! -x "sign" ]] && chmod +x sign

# Check if word list is accessible
[[ ! -r "/usr/share/dict/words" ]] && { echo "ERROR: cannot read '/usr/share/dict/words' word list" ; exit ; }

# Sign words > sort signed rep > squash words > count anagrams > sort by number of anagrams > output top 8
./sign < /usr/share/dict/words | sort | awk -f squash.awk | awk '{ print NF " " $0 }' | sort -nr | head -n 8
