#!/bin/bash

usage() {
	echo "Intended Usage: organiseMusic is designed to organize files of the format 'artist - song.mp3' into ./artist/song.mp3"
}

# Function to move a file to a new destination and create a unique filename by appending an integer if the file already
# exists
# Usage: move_file dest target.mp3 [ext#]
# For this lab, this function assumes filename ends with .mp3
# Optional ext# is used for recursively making a unique filename with an extending number
move_file() {
	if [ $# -lt 2 ] ; then
		echo "ERROR: move_file() function used improperly" ; exit
	fi
	song=$2
	ext=0
	if [ $# -gt 2 ] ; then
		new_song=${song::-4}_$3${song: -4}
		ext=$3
	else
		new_song=$song
	fi
	# If the current file already exists
	if [ -f "$new_song" ] ; then
		((ext=ext+1))
		# Recurse with incremented extension integer
		move_file "$1" "$song" $ext
		return
	fi
	# Attempt to move song to it's new directory
	mv "$1" "$new_song"
	# Error handle mv command call
	if [ $? -ne 0 ] ; then
		echo "ERROR: Failed move file to ./$new_song" ; exit
	fi
	echo "Created new file: $new_song"
}

renamed=0

# Read through each file in the directory
while read fullsong ; do
	# If the filename matches the pattern of two words separated by a - and is a .mp3 file
	if [[ "$fullsong" = *-*.mp3 ]] ; then
		((renamed=renamed+1))
		artist=""
		song=""
		switch=0
		# Iterate through each word in the filename to split it by the - char
		for word in $fullsong ; do
			# Switch which variable to append words to once hitting the -
			if [[ "$word" == "-" ]] ; then
				switch=1
			# Build artist string
			elif (( $switch == 0 )) ; then
				artist+="$word "
			# Build song string
			else
				song+="$word "
			fi
		done
		# Remove last space char from both strings
		artist=${artist::-1}
		song=${song::-1}
		# Check if directory doesn't already exists
		if [ ! -d "./$artist" ] ; then
			# If not, make it
			mkdir "$artist"
		fi
		# Move song into new directory
		move_file "$fullsong" "$artist/$song"
	fi
done <<<$(ls -1)

# check for files renamed
if (( renamed == 0 )) ; then
	echo "ERROR: No files found to rename" ; usage ; exit
else
	echo "Successfully organized $renamed songs"
fi

