#!/bin/bash

usage() {
	echo "Intended Usage: organiseMusic is designed to organize files of the format 'artist - song.mp3' into ./artist/song.mp3"
}

move_file() {
	song=$2
	ext=0
	if [ $# -gt 2 ] ; then
#TODO: Fix renaming to replace last number instead of appending more _# each iteration
		song=${song::-4}_$3${song: -4}
		ext=$3
	fi
	# If the current file already exists
	if [ -f "$song" ] ; then
		((ext=ext+1))
		move_file "$1" "$song" $ext
		return
	fi
	mv "$1" "$song"
	if [ $? -ne 0 ] ; then
		echo "ERROR: Failed move file to ./$2" ; exit
	fi
}

renamed=0

# Read through each file in the directory
while read fullsong ; do
	# If the filename matches the pattern of two words separated by a - and is a .mp3 file
	if [[ "$fullsong" = *-*.mp3 ]] ; then
		((renamed=renamed+1))
		artist=""
		song=""
		switch=0
		echo "Found song to rename: $fullsong"
		# Iterate through each word in the filename to split it by the - char
		for word in $fullsong ; do
			# Switch which variable to append words to once hitting the -
			if [[ "$word" == "-" ]] ; then
				switch=1
			# Build artist string
			elif (( $switch == 0 )) ; then
				artist+="$word "
			# Build song string
			else
				song+="$word "
			fi
		done
		# Remove last space char from both strings
		artist=${artist::-1}
		song=${song::-1}
		# Check if directory doesn't already exists
		if [ ! -d "./$artist" ] ; then
			# If not, make it
			mkdir "$artist"
		fi
		# Move song into new directory
		move_file "$fullsong" "$artist/$song"
	fi
done <<<$(ls -1)

# check for files renamed
if (( renamed == 0 )) ; then
	echo "ERROR: No files found to rename" ; usage ; exit
else
	echo "Successfully organized $renamed songs"
fi

